### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by kocierik** [kocierik/animalHouse#1]
# RoadMap

- ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) Obbligatorio
- ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) Facoltativo
  
<b>tre applicazioni:</b>
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) Game, informazioni e curiosità sui propri cari, fare giochi a tema animalesco, e confrontare prodotti dello store. Mobile first, solo online, nessuno database
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) Front-office, applicazione per i clienti, mobile first, attività di accesso e uso di tutti i servizi online e per la prenotazione di quelli in presenza per i clienti regulare
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) Back-office, applicazione per gli impiegati dell'azienda che, sede per sede, inseriscono e rimuovono servizi e prodotti, gestiscono prezzi e descrizioni, controllano e modificano le prenotazioni..
  

## Game
- [x] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) <b> Curiosita' & Informazioni</b>
- [x] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) <b> Video su YT </b>
- [x] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) <b> Pubblicita' </b>
- [x] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) <b>Quiz: usando la stessa API delle curiosità il sistema genera domande a caso</b>
- [x] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)  Memory: usando API di immagini il sistema crea coppie di immagini e le dispone nascoste. L'utente deve scoprirle a coppie
- [x] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)  Impiccato: usando API di dizionari di termini sugli animali il sistema presenta una parola complessa che l'utente deve indovinare lettera per lettera
- [x] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)  Scova le differenze: due immagini simili ma con piccoli particolari differenti che l'utente deve scovare (SVG)
- [x] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) Snake

## Front-office

Il front-office è un'applicazione web tradizionale, solo online, sia per device mobili sia per PC, orietata a fornire accesso ai prodotti e ai servizi offerti dall'azienda.
<b>Servizi di comunità:
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) leaderboard con punteggi dei vari giochi del game
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+)  bacheca eccolo qua 
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) bacheca cerco partner
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) bacheca aiutatemi
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) ecc
  </b>
<b>e-commerce: catalogo ragionato e diviso per sezioni di prodotti per animali acquistabili online: 
  
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) cibo
  - [ ]  ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) prodotti sanitari
  - [ ]  ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) accessoristica 
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) cuccioli
  </b>

<b>Servizi in presenza:  ogni servizio prevede una parte di illustrazione del servizio e una parte di accesso e prenotazione (secondo sede e disponibilità) 
  
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) veterinario
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) dog sitter 
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) toelettatura
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) pensione estiva
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) psicologo
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) visita a domicilio per animali soli
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) ecc   
  </b>
  
  - Servizi online
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) videoconferenze con l'esperto
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) videoconferenze con veterinario
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) videoconferenze con il proprio animale in ospedale
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) videoconferenze in pensione
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) ecc
  
  
## Back-office
Il back-office è la parte dell'applicazione che permette agli amministratori di gestire i dati dei clienti e abilitare e configurare i servizi e i prodotti. E' un'applicazione web tradizionale, solo online, principalmente per PC.

<b> Anagrafica clienti: per gestire le informazioni sui clienti: 
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) registrazione
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) login
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) cambio password
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) reset password
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) cancellazione
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) preferenze
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) animali preferiti
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) punteggio dei giochi
</b>

<b> Servizi di comunità: 
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+)  controllare messaggi in bacheca
- [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) cancellare messaggi in bacheca
</b>

<b>
Gestione e-commerce: 
  
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) aggiungere prodotti
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) togliere prodotti
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) prezzi
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) descrizioni
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) categoria
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) sottocategorie
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) immagine (URI online)
    - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) uploadata sul file system del server
</b>

<b>
Servizi in presenza: 
  
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) prenotare servizi in presenza
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) modificare prenotazioni
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) cancellare prenotazioni
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) visualizzare disponibilità
  - [ ] ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) calendari separati ( in una sede posso avere molti veterinari, molte camere della pensione
</b>

- Servizi online
  - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) prenotare servizi online
  - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) moficare prenotazioni
  - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) cancellare prenotazioni
  - [ ] ![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+) controllare disponibilità
